title: My course lmao
description: don't
template:
  repo: my-course-lmao-template
  name: my-course-lmao
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
